### ISSUE TITLE
Some Issues

### ISSUE THREAD

**Issue by ujc75573** [tontyoutoure/DOTA2-AI-Fun#35]
Hi,

I hope this message finds you well. I wanted to make a comment in Steam, but I don't know how, so I'm going to post it here.

After playing with the map, here are some of the issues I found so far:

1. The scoreboard at the top is kind of messed up because the spacing is not balanced (the left side has little space, while the right side has too much space). Please click the link to see the image: http://i68.tinypic.com/33yon6v.jpg

2. I also noticed that after hero selection (where you buy initial items), the loading screen is not showing the models of heroes.

3. Lastly, I found that the Bot AI being used is the default. Is there a way to use a custom Bot AI (Ranked Matchmaking AI) from the workshop? I also tried Rage Trigger and it's working, but I like Ranked Matchmaking AI more.

4. Some bots (no exact hero) at the beginning just stay at the fountain unless I move them.

I know that these issues are not critical, but it would definitely improve the game if they are addressed.

**Comment by tontyoutoure** [comment]
1. I cannot see your pic. The top bar scoreboard is imported from the offical 10v10 map. Of course there are space for improvement, but it clearly is not our priority (which is adding more heroes).
2. The whole hero-model-wearable thing is a bunch of mess. But I haven't met the situation you described, could you elaborate? Like what hero you use?
3. We will try to add more options for bots in the future.
4. Which of bots? Will the get out of fountain eventually?

**Comment by ujc75573** [comment]
Hi,

1. How about this one? http://i.imgur.com/ZzRxeQa.jpg

2. It's like this one (bottom left corner), except the image of all heroes are blank: https://i.ytimg.com/vi/uUkR_ksNGZU/maxresdefault.jpg

3. Thanks.

4. Sometimes, it's Sven, Tiny, Necro, Chaos, etc.

**Comment by ujc75573** [comment]
Hi,

I have an update. It looks like the bugs with other Bot AIs not working have been resolved. I'm able to use other AIs now. Aside from that, I noticed that at late game, other bots stay at the secret shop (e.g., Bounty Hunter, Zeus, etc.).

**Comment by ujc75573** [comment]
Update:

I'm able to use other Bot AIs now, but the hero selection they are using is still default. Also, I noticed that the map is not using the updated stats for heroes and items. If it's not too much to ask, can you update them to match the latest version?

**Comment by tontyoutoure** [comment]
@ujc75573 I'm finishing my Ph.D thesis and there should't be updates within months. I'm sorry for keep you waiting. 
Still thanks for your feedback. I'll take hands in them when I get time.

**Comment by tontyoutoure** [comment]
@ujc75573 I'm finishing my Ph.D thesis and there wouldn't be updates within months. I'm sorry for keep you waiting.
Still thanks for your feedback. I'll take hands in them when I get time.

**Comment by tontyoutoure** [comment]
@ujc75573 I know how to enable more bots. How did you use other Bot AI exactly?

**Comment by ujc75573** [comment]
Hi,

Sorry for the late reply. To answer your question, I put your map into the **addons** (dota 2 beta\game\dota_addons) folder. From there, I copy the files for Bot AIs into the **script** folder (\scripts\vscripts\bots).

However, when some of the developers changed the bot names, I noticed that only 5 of their bots get added. The remaining 5 is from the default bots. If you can make an adjustment in your code to utilize Bot AIs, I'm sure that a lot of players will enjoy the map more.

**Comment by tontyoutoure** [comment]
@ujc75573 thing is seemingly valve did not open the bot api in custom games. Of course I can simulate some bot think by using thinking functions, but too much thing in lua visual machine will cause the game running speed. By now I can only fix some most severe issues for bots, like they were not attacking tower and picking rune.

**Comment by ujc75573** [comment]
I see. Although, is it possible to integrate the Bot AIs in your mod? For example, the mod below is able to use the [Ranked Matchmaking AI](http://steamcommunity.com/sharedfiles/filedetails/?id=855965029) by adamqqq:

**The Same Hero Mode**
http://steamcommunity.com/sharedfiles/filedetails/?id=1142834050

You can also use [BOT EXPERIMENT Credit:FURIOUSPUPPY](http://steamcommunity.com/sharedfiles/filedetails/?id=837040016) by привет! Аризона.

Putting that aside, I noticed that when I use Angelic Alliance (v1.55 of your mod) with Phantom Lancer the game gets laggy. I checked my FPS, and it's still around 55 to 60. This doesn't happen in the previous versions. Any ideas?

**Comment by tontyoutoure** [comment]
It's a bot script, not a custom game.

**Comment by ujc75573** [comment]
Yes, I noticed. That's why I asked if it's possible to integrate the Bot AIs (script) in your mod. This way, your mod will no longer use the default Bot AIs.
